config/routes.rb
require 'resque/server'

CoveElan::Application.routes.draw do

  match '/thumb/:filename.:extension/:offset' => 'thumbs#show'
  resources :meta_data_fields
  resources :meta_data_groups

  devise_for :users

  resources :corpora
  resources :projects
  resources :work_documents
  resources :templates
  resources :user_assets do
    member do
      get "download"
    end
    resources :frames
    
  end

  match 'documents/:id/download' => 'documents#download', :as => :download_document
  match 'user_assets/:id/download' => 'user_assets#download', :as => :download_asset
  match 'templates/:id/update_meta_data' => 'templates#update_meta_data'

  match 'templates/:id/duplication' => 'templates#duplication'

  authenticated do
      root :to => 'welcome#index'
      mount Resque::Server.new, :at => "/resque"
  end

  root :to => 'landing#index'

end

app/models/user_asset.rb
require 'carrierwave/orm/activerecord'

class UserAsset < ActiveRecord::Base
  belongs_to :user
  belongs_to :capture

  has_many :user_asset_assignments

  has_many :templates, :through => :user_asset_assignments, :source => :user_asset_assignable, :source_type => 'Template'

  has_many :meta_data_group_assignments, :as => :meta_data_group_assignable
  has_many :meta_data_groups, :through => :meta_data_group_assignments

  has_many :meta_data_values, :as => :meta_data_valuable

  mount_uploader :file_name, UserAssetUploader

  def asset_type
    type_info =  %x[file --mime -b #{file_name.path} ]
    type_info.split(';')[0].split('/')[0]
  end

  def self.match_basename(basename)
    where(["file_name like ?", "%#{basename}"  ])
  end

  def name
    self.title.blank? ? File.basename(file_name.to_s) : self.title
  end
end

app/models/user_asset_helper.rb
class UserAssetHelper

  def self.reset_user_asset_assignments map_object, user_asset_assignments

    #Destroy existing assignments
    UserAssetAssignment.where(:user_asset_assignable_id => map_object.id,
      :user_asset_assignable_type => map_object.class.name).each do |asset|
        asset.destroy
      end

    #Remove empty elements from input array
    user_asset_assignments.reject! { |e| e.empty? }

    #Create new assignments
    user_asset_assignments.each do |asset|
      UserAssetAssignment.create(:user_asset_id => asset,
        :user_asset_assignable_type => map_object.class.name,
        :user_asset_assignable_id => map_object.id)
    end
  end

end

app/controllers/user_assets_controller.rb
class UserAssetsController < ApplicationController
  before_filter :authenticate_user!
  
  def index
    @user_assets = UserAsset.order('id DESC').all

    respond_to do |format|
      format.html # index.html.erb
    end
  end

  def show
    @user_asset = UserAsset.find(params[:id])

    respond_to do |format|
      format.html {render}
      format.any {send_file @user_asset.file_name.path}
    end
  end

  def edit
    @user_asset = UserAsset.find(params[:id])
    @meta_data_groups = @user_asset.meta_data_group_assignments
    @meta_data_fields = MetaDataHelper.get_field_objects @user_asset
  end

  # GET /assets/new
  def new
    @user_asset = UserAsset.new

    respond_to do |format|
      format.html # new.html.erb
    end
  end

  def update
    @user_asset = UserAsset.find(params[:id])

    if params[:user_asset][:meta_data_gropu_ids]
      MetaDataHelper.reset_group_assignments(@user_asset, params[:user_asset][:meta_data_group_ids])
    end

    @user_asset.update_attributes(params[:user_asset])
    respond_to do |format|
      if @user_asset.errors.count == 0 and @user_asset.save
        format.html { redirect_to @user_asset, notice: 'Asset was successfully updated.' }
      else
        format.html { render action: "edit" }
      end
    end
  end

  def create
    @user_asset = UserAsset.new(:file_name => params[:user_asset][:file_name],
      :user_id => current_user.id,
      :content_type => params[:user_asset][:file_name].content_type,
      :headers => params[:user_asset][:file_name].headers)


    @user_asset.save
    
    respond_to do |format|
      if @user_asset.valid?
        puts @user_asset.inspect
        format.html { redirect_to @user_asset, notice: 'Asset was successfully saved.' }
      else
        format.html { render action: "new" }
      end
    end
  end

  def destroy
    UserAsset.find(params[:id]).destroy

    respond_to do |format|
      format.html { redirect_to user_assets_url }
    end
  end

  def download
    @user_asset = UserAsset.find(params[:id])
    send_file @user_asset.file_name.path
  end
end

app/helpers/user_assets_helper.rb
module UserAssetsHelper
  def display_asset(model)

    partial = "user_assets/#{model.asset_type}"

    if lookup_context.find_all("user_assets/_#{model.asset_type}").any?  
      render :partial => partial, :object => model
    else
      render :partial => 'user_assets/unknown', :object => model
    end
  end
end

app/views/user_assets/_form.html.erb
<%= simple_form_for @user_asset, :html => {:multipart => true, :class => 'form-horizontal'} do |f| %>
  <% if @user_asset.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user_asset.errors.count, "error") %> prohibited this user_asset from being saved:</h2>

      <ul>
      <% @user_asset.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.input :title %>
  <%= f.input :needs_review, :label => "Needs Review" %>
    <%= f.association :meta_data_groups %>

    <%= f.file_field :file_name %>

  <div class="actions">
    <%= f.submit "Update Asset" %>
  </div>
<% end %>

app/views/user_assets/_image.html.erb
<img src="<%= user_asset_path(id:image.id, format:'jpg')%>" class="main"/>

app/views/user_assets/_meta_data.erb
<%= simple_form_for(@user_asset) do |f| %>
    <%= f.association :meta_data_groups %>
    <%= render :partial => 'meta_data_fields/fields_form', :locals => { :f => f, :object => @user_asset, :fields => @meta_data_fields } %>

    <%= f.submit %>
<% end %>

app/views/user_assets/_unknown.html.erb
Preview not available for this type of asset.

<%= link_to "Download", user_asset_path( id: unknown.id, format: File.extname(unknown.file_name.path).gsub('.','')) %>

app/views/user_assets/_video.html.erb
<video class="main video-js vjs-default-skin" controls preload="auto" data-setup='{"techOrder": ["flash"]}' width="480" height="270">
  <source src="<%= user_asset_url(id:video.id, format: :mp4 )%>" type='video/mp4'>
</video>

app/views/user_assets/edit.html.erb
<p>
  <b>File Name:</b>
  <%= File.basename(@user_asset.file_name.to_s) %>
</p>

<div class="row">

<div class="span12">
  <div id="viewer">
    <%= render 'form' %>
    <%= display_asset(@user_asset) %>
  </div>
</div>
</div>

app/views/user_assets/index.html.erb
<h1>Files</h1>

<%= link_to 'New User Asset', new_user_asset_path %>


<table class="table table-striped table-bordered table-condensed">
  <tr>
    <th>File Name</th>
    <th></th>
    <th></th>
  </tr>

<% @user_assets.each do |asset| %>
  <tr>
    <td><%= link_to asset.name, asset %></td>
    <td><%= link_to 'Edit', edit_user_asset_path(asset) %>
  <td><%= link_to 'Destroy', asset, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

app/views/user_assets/new.html.erb
<h1>New Asset</h1>

<%= render 'form' %>

<%= link_to 'Back', user_assets_path %>

app/views/user_assets/show.html.erb
<h1 class="page-header">
  <%= @user_asset.asset_type.blank? ? "File" : @user_asset.asset_type.humanize %>: <small> 
  <%= simple_form_for @user_asset, :remote => true do |f| %>
    <%= f.input :title, :placeholder => File.basename(@user_asset.file_name.to_s), :label => false %>
    <%= f.input :needs_review, :as => :hidden, :input_html => {:disabled => 'disabled', :class => 'review_field', :value => !@user_asset.needs_review } %>

      <a href="#" id="review_button" data-toggle="button" class="<%= "btn #{' btn-danger active' if @user_asset.needs_review}" %>"><%= @user_asset.needs_review ? "Needs Review" : "Mark for Review"%></a>
    <% end %>
</h1>
<div class="row">
  <div class="span8">
    <div class="row">
      <div id="preview" class="span8">
        <%= display_asset(@user_asset) %>
      </div>
    </div>

    <div class="row">
      <div class="span8">
        Notes Down here
      </div>
    </div>
  </div>
    <div id="metadata" class="span4" >

        <%= simple_form_for @user_asset,
          :url => url_for(:action => 'update_meta_data', :controller => 'user_assets'),
          :method => 'post', :html => {:class => "zform-horizontal"}  do |f| %>

        <ul class="unstyled">

          <% @user_asset.meta_data_groups.each do |group| %>
            <li>
              <%=render :partial => 'meta_data_fields/fields_form', :locals => { :f => f, 
              :fields => group.meta_data_fields,
              :group => group } %>

            </li>
          <% end %>
        </ul>
          <%= f.button :submit %>
        <% end %>
    </div>
</div>

<script>
  $('.edit_user_asset').bind('ajax:success', function(){
    $('.review_field').attr('disabled', true);
    
    $('#user_asset_title').parents('.control-group').addClass('success');
});

$("#review_button").bind('click', function(){
  var button = $("#review_button");
  button.toggleClass('btn-danger');

  if (button.hasClass('active')) {
    button.text('Needs Review');
    $('.review_field').val('f');
  } else {
  button.text('Request Review');
  $('.review_field').val('t');

 }
 $('.review_field').removeAttr('disabled');
 $('.edit_user_asset').submit();
});
</script>