config/routes.rb
require 'resque/server'

CoveElan::Application.routes.draw do

  match '/thumb/:filename.:extension/:offset' => 'thumbs#show'
  resources :meta_data_fields
  resources :meta_data_groups

  devise_for :users

  resources :corpora
  resources :projects
  resources :work_documents
  resources :templates
  resources :user_assets do
    member do
      get "download"
    end
    resources :frames
    
  end

  match 'documents/:id/download' => 'documents#download', :as => :download_document
  match 'user_assets/:id/download' => 'user_assets#download', :as => :download_asset
  match 'templates/:id/update_meta_data' => 'templates#update_meta_data'

  match 'templates/:id/duplication' => 'templates#duplication'

  authenticated do
      root :to => 'welcome#index'
      mount Resque::Server.new, :at => "/resque"
  end

  root :to => 'landing#index'

end

app/views/templates/_form.html.erb
<%= simple_form_for(@template) do |f| %>
  <% if @template.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@template.errors.count, "error") %> prohibited this template from being saved:</h2>

      <ul>
      <% @template.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <%= f.input :name, :input_html => { :value => @template.name_or_id } %>

    <%= f.association :meta_data_groups %>

    <%= f.association :user_assets, :label_method => lambda { |x| File.basename(x.file_name.to_s) } %>

    <%= render :partial => 'meta_data_fields/fields_form', :locals => { :f => f, :object => @template, :fields => @meta_data_fields } %>

    <%= f.button :submit %>
<% end %>

app/views/templates/_template.html.erb
<div class="row span10">

  <div class="page-header">
		<h2>
      <%=link_to template.name_or_id, download_document_path(template.document) %><small> <%=link_to "Edit", edit_template_path(template) %></small>
    </h2>
  </div>


  <% unless template.work_documents.empty? %>
      <ul class="nav nav-tabs">
        <li class="active"><a href="#home<%=t_index%>" data-toggle="tab">Home</a></li>
        <li><a href="#tiers<%=t_index%>" data-toggle="tab">Tiers</a></li>
        <li><a href="#media<%=t_index%>" data-toggle="tab">Media</a></li>
        <li><a href="#assets<%=t_index%>" data-toggle="tab">Assets</a></li>
        <li><a href="#work_documents<%=t_index%>" data-toggle="tab">Work Documents</a></li>
      </ul>

      <div class="tab-content">
        <div class="tab-pane active" id="home<%=t_index%>">
          <div class="accordion" id="template_body_accordion">
            <% template.meta_data_values.each_with_index do |mv, index| %>
              <div class="accordion-group">
                <div class="accordion-heading">
                  <a class="accordion-toggle" data-toggle="collapse" data-parent="#template_body_accordion" href="#template_body_collapse<%=index%>"><%=mv.meta_data_field.name%></a>
                </div>

                <div id="template_body_collapse<%=index%>" class="accordion-body collapse in" style="height: 0px;">
                  <div class="accordion-inner">
                    <p><%= MetaDataHelper.get_value_as_string mv %></p>
                  </div>
                </div>
              </div>
            <% end %>
          </div>
        </div>

        <div class="tab-pane" id="tiers<%=t_index%>">
          <h4>Tiers</h4>
          <dl class="dl-horizontal">
          <% template.work_documents.first.document.tiers.each do |tier| %>
              <dt><%= tier[:tier_id] %></dt>
            <% end %>
          </dl>
        </div>

        <div class="tab-pane" id="media<%=t_index%>">
          <h4>Media</h4>
          <ul>
            <% template.work_documents.first.document.media_descriptors.each do |media_descriptor| %>
              <li><%= media_descriptor[:media_url] %></li>
            <% end %>
          </ul>
        </div>

        <div class="tab-pane" id="assets<%=t_index%>">
              <h4>Assets</h4>
                <% template.user_assets.each_with_index do |asset, index| %>
                  <p><%= link_to File.basename(asset.file_name.to_s), eval(asset.class.name.underscore.downcase + '_path('+asset.id.to_s+')') %></p>
                  <ul class="nav nav-tabs">
                    <li class="active"><a href="#meta_data<%=index%>" data-toggle="tab">Meta Data</a></li>
                    <li><a href="#download<%=index%>" data-toggle="tab">Download</a></li>
                    <li><a href="#view<%=index%>" data-toggle="tab">View</a></li>
                  </ul>

                  <div class="tab-content">
                    <div class="tab-pane active" id="meta_data<%=index%>">
                      <div class="accordion" id="asset_body_accordion">
                        <% asset.meta_data_values.each_with_index do |mv, index| %>
                          <div class="accordion-group">
                            <div class="accordion-heading">
                              <a class="accordion-toggle" data-toggle="collapse" data-parent="#template_body_accordion" href="#template_body_collapse<%=index%>"><%=mv.meta_data_field.name%></a>
                            </div>

                            <div id="asset_body_collapse<%=index%>" class="accordion-body collapse in" style="height: 0px;">
                              <div class="accordion-inner">
                                <p><%= MetaDataHelper.get_value_as_string mv %></p>
                              </div>
                            </div>
                          </div>
                        <% end %>
                      </div>
                    </div>
                    <div class="tab-pane" id="download<%=index%>">
                      <p><a href="/user_assets/<%=asset.id%>/download">Download....</a></p>
                    </div>
                    <div class="tab-pane" id="view<%=index%>">
                      <%= display_asset(asset) %>
                    </div>
                  </div>
                <% end %>
        </div>

        <div class="tab-pane" id="work_documents<%=t_index%>">
          <h4>Recent Uploads</h4>
          <% template.work_documents.order("created_at DESC").limit(3).each do |work_document| %>
            <ul>
              <li class="document-list-item">
                <%=link_to "#{work_document.user.full_name} #{work_document.created_at.strftime('%m/%d/%Y %H:%M:%S')}" ,
                  download_document_path(work_document.document), 
                  :id => File.basename(work_document.document.eaf.to_s), :class => 'download-work_document' %> 
                <%=link_to "", work_document, :class=> 'icon-eye-open view-work_document-link', 
                  :id => File.basename(work_document.document.eaf.to_s) %>
              </li>
            </ul>
          <% end %>
      </div>
      </div>
  
          <% else %>
            <h4>This template contains no work documents.</h4>
          <% end %>
</div>

app/views/templates/_template_meta_data.erb
<%= simple_form_for @template,
   :url => url_for(:action => 'update_meta_data', :controller => 'templates'),
   :method => 'post' do |f| %>
  <% if @template.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@template.errors.count, "error") %> prohibited this template from being saved:</h2>

      <ul>
      <% @template.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="span10">
    <%= render :partial => 'meta_data_groups/groups_form', :locals => { :f => f, :object => @template } %>
  </div>

  <div class="span10">
    <%= f.button :submit %>
  </div>

<% end %>

app/views/templates/duplication.html.erb
<h1>Template Duplication Viewer</h1>

<style stype="text/css">
  .chart rect {
    stroke: #FFF;
  }

  .viewer_wrapper {
    height: 60px;
    margin: 0 0 5px 0;
    padding: 5px 5px 0 5px;
  }

</style>

<% viewer_index = 0 %>

<div class="span12" id="wrapper" style="margin-bottom: 200px;">
<% @duplicates.each do |tier, annotation| %>
  <div class="span12">
	<h3>Tier <%=tier%> </h3>
  <% annotation.each do |k,v| %>
		<% unless v.empty? %>
			<p>Overlapping annotations for "<%=k%>" </p>
			<br />
			<% v.each_with_index do |overlap, index| %>
				<%= overlap.inspect %>
				<% viewer_index += 1 %>
				<div class="span12">
					<div class="viewer_wrapper" id="viewer_<%=viewer_index%>"></div>
				</div>
				<script>
					$().AnnotationOverlap( <%= overlap %>, <%=viewer_index%> );
				</script>
			<% end %>
		<% else %>
			<p>No overlap found for "<%=k%>"</p>
		<% end %>
  <% end %>
  </div>
<% end %>
</div>

app/views/templates/edit.html.erb
<h1>Editing template</h1>

<%= render 'form' %>

<%= link_to 'Show', :action => "show", :id => @template.id %> |
<%= link_to 'Back', templates_path %>

app/views/templates/index.html.erb
<h1>Listing templates</h1>

<table>
  <tr>
    <th>Template Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

  <tr>
    <th>Template Documents</th>
  </tr>

<% @templates.each do |template| %>
  <tr>
    <td><%= template.name_or_id %></td>
    <td><%= link_to 'Show', template %></td>
    <td><%= link_to 'Edit', edit_template_path(template) %></td>
    <td><%= link_to 'Destroy', template, confirm: 'Are you sure?', method: :delete %></td>
  </tr>

<% end %>
</table>

app/views/templates/show.html.erb
<div class="row">

  <div id="picker" class="span2">
    <p>
  <b>Template Name:</b>
  <%= @template.name_or_id %>
</p>
  </div>

  <div id="metadata" class="span4">

    <p>
  <b>Assigned Template Meta Data Groups:</b>
  <% @template.meta_data_groups.each do |group| %>
    <p><%= group.name %></p>
  <% end %>
</p>

<p>
  <b>Associated Projects:</b>
  <ul>
    <% @template.projects.each do |p| %>
      <li><%= p.name %></li>
    <% end %>
  </ul>
</p>

<div class="span4">
  <%= render 'template_meta_data' %>
</div>

  </div>

  <div id="tracks" class="span6">

<p>
  <b>Template Media:</b>
  <ul>
    <% @template.document.media_descriptors.each do |media| %>
      <li><%= media[:media_url] %></li>
    <% end %>
  </ul>
</p>

<p>
  <b>Template Tiers:</b>
  <ul>
    <% @template.document.tiers.each do |tier| %>
      <li><%= tier[:tier_id] %></li>
    <% end %>
  </ul>
</p>


  </div>


</div>

<%= link_to 'Edit', edit_template_path(@template) %> |
<%= link_to 'Back', templates_path %>