config/routes.rb
require 'resque/server'

CoveElan::Application.routes.draw do

  match '/thumb/:filename.:extension/:offset' => 'thumbs#show'
  resources :meta_data_fields
  resources :meta_data_groups

  devise_for :users

  resources :corpora
  resources :projects
  resources :work_documents
  resources :templates
  resources :user_assets do
    member do
      get "download"
    end
    resources :frames
    
  end

  match 'documents/:id/download' => 'documents#download', :as => :download_document
  match 'user_assets/:id/download' => 'user_assets#download', :as => :download_asset
  match 'templates/:id/update_meta_data' => 'templates#update_meta_data'

  match 'templates/:id/duplication' => 'templates#duplication'

  authenticated do
      root :to => 'welcome#index'
      mount Resque::Server.new, :at => "/resque"
  end

  root :to => 'landing#index'

end

app/models/project.rb
class Project < ActiveRecord::Base
  has_many :project_templates
  has_many :templates, :through => :project_templates

 	has_many :meta_data_values, :as => :meta_data_valuable, :dependent => :destroy
	has_many :meta_data_group_assignments, :as => :meta_data_group_assignable
	has_many :meta_data_groups, :through => :meta_data_group_assignments

  belongs_to :user
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  before_filter :authenticate_user!

  def index
    @projects = Project.all

    respond_to do |format|
      format.html # index.html.erb
    end
  end

  # GET /projects/1/edit
  def edit
    @project = Project.find(params[:id])
    
    @meta_data_groups = @project.meta_data_group_assignments

    @selected_templates = @project.templates
    @meta_data_fields = MetaDataHelper.get_field_objects @project
  end

  # GET /projects/new
  def new
    @project = Project.new

    respond_to do |format|
      format.html # new.html.erb
    end
  end

  # POST /projects
  def create
    @project = Project.new(params[:project])

    @meta_data_groups = @project.meta_data_group_assignments

    respond_to do |format|
      if @project.save!
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
      else
        format.html { render action: "new" }
      end
    end
  end

  def show
    @project = Project.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
    end
  end

  # PUT /projects/1
  def update
    @project = Project.find(params[:id])
    @selected_meta_data_group = @project.meta_data_group
    @selected_templates = @project.templates
    @meta_data_fields = MetaDataHelper.get_field_objects @project

    @project.update_attributes(:name => params[:project][:name])

    MetaDataHelper.validate_and_save_field_values @meta_data_fields, @project, params[:project][:meta_data_field] unless params[:project][:meta_data_field].nil?

    @project.template_ids = params[:templates][:templates]

    @project.meta_data_group = MetaDataGroup.find(params[:project][:meta_data_group]) 


    respond_to do |format|
      if @project.errors.count == 0 and @project.save
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
      else
        format.html { render action: "edit" }
      end
    end
  end

  # DELETE /projects/1
  def destroy
    @project = Project.find(params[:id])
    @project.destroy

    respond_to do |format|
      format.html { redirect_to projects_url }
    end
  end
end

app/views/projects/_form.html.erb
<%= simple_form_for(@project) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <br /><br />

  <div class="field">
    <%= f.label :name %>
    <br />
    <%= f.text_field :name, :value => @project.name %>
  </div>

  <div class="field">
    <%= f.label :Templates %>
    <br />
    <%= collection_select(:templates, :templates, ::Template.all(:order => 'name'), :id, :name, 
    @selected_templates.blank? ? {} : { :selected => @selected_templates.map {|j| j.id} }, { :multiple => true }) %>
  </div>

  <div class="field">
    <%= f.association :meta_data_groups %>
  </div>

  <div class="field">
    <%= render :partial => 'meta_data_fields/fields_form', :locals => { :f => f, :object => @project, :fields => @meta_data_fields } %>
  </div>

  <div class="actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<h1>Editing project</h1>

<%= render 'form' %>

<%= link_to 'Show', :action => "show", :id => @project.id %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<h1>Projects</h1>

<%= link_to 'New Project', new_project_path %>

<% @projects.each do |p| %>
  <div class="page-header">
    <h2>
      <%= p.name %>
    </h2>
    <p><%= link_to 'Edit', edit_project_path(p) %> | <%= link_to 'Destroy', p, confirm: "Are you sure?", method: :delete %></p>
  </div>

  <div class="row">
    <div class="span4">
      <h4>Project Templates</h4>
      <% p.templates.each do |t| %>
        <p><%= link_to t.name, template_path(t) %></p>
      <% end %>
    </div>

    <div class="span4">
      <h4>Assigned Meta Data Groups</h4>
      <% p.meta_data_group_assignments.each do |assignment| %>
        <p><%= assignment.meta_data_group.name %></p>
      <% end %>
    </div>
  </div>
<% end %>

app/views/projects/new.html.erb
<h1>New project</h1>

<%= render 'form' %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Project Name:</b>
  <%= @project.name %>
</p>

<p>
  <b>Associated Templates:</b>
  <ul>
    <% @project.templates.each do |t| %>
      <li><%= t.name_or_id %></li>
    <% end %>
  </ul>
</p>


<%= link_to 'Edit', edit_project_path(@project) %> |
<%= link_to 'Back', projects_path %>