config/routes.rb
require 'resque/server'

CoveElan::Application.routes.draw do

  match '/thumb/:filename.:extension/:offset' => 'thumbs#show'
  resources :meta_data_fields
  resources :meta_data_groups

  devise_for :users

  resources :corpora
  resources :projects
  resources :work_documents
  resources :templates
  resources :user_assets do
    member do
      get "download"
    end
    resources :frames
    
  end

  match 'documents/:id/download' => 'documents#download', :as => :download_document
  match 'user_assets/:id/download' => 'user_assets#download', :as => :download_asset
  match 'templates/:id/update_meta_data' => 'templates#update_meta_data'

  match 'templates/:id/duplication' => 'templates#duplication'

  authenticated do
      root :to => 'welcome#index'
      mount Resque::Server.new, :at => "/resque"
  end

  root :to => 'landing#index'

end

app/models/work_document.rb
class WorkDocument < ActiveRecord::Base
	after_create :async_template_identify

	has_one :document, :as => :documentable, :dependent => :destroy

	belongs_to :user

	accepts_nested_attributes_for :document

	belongs_to :template

  state_machine :initial => :waiting do

    event :process do
      transition :waiting => :processing
    end

    event :finish do
      transition :processing => :ready, :if => :document_processed?
      transition all => :failed
    end

    state :processing

  end

  def document_processed?
    document.valid?
  end

  def async_template_identify
    Resque.enqueue(TemplateIdentifer, self.id)
  end

  def media_assets

    document.annotation_document.header.media_descriptors.map {|desc| [desc.media_url, UserAsset.match_basename(File.basename(desc.media_url)) ] }

  end


	#belongs_to :project
	def clone_for_template
    elan_xml = ElanParser::XML::Build.new
    elan_xml.build_eaf_document(self.document.annotation_document_id)
		
		new_doc = Document.new(:eaf => self.document.eaf)

    new_doc.create_annotation_document if new_doc.eaf?

		new_doc.annotation_document.tiers.each { |t| t.annotations.each { |a| a.destroy } }

		new_doc.save

		template = Template.create(:document => new_doc, :user_id => self.user_id)

		return template
	end


	#Look thru the document media descriptors and tiers to identify if this template becomes a template or not
	def template_identify
		return if !self.document or !self.document.valid? or !self.template_id.nil?

		self_tiers = Array.new
		self_media = Array.new

		self.document.tiers.each { |t| self_tiers.push(t[:tier_id]) }
		self.document.media_descriptors.each { |m| self_media.push(m[:media_url]) }

		is_template = true

		# Determine if there is a document with an existing template
		Template.all.each do |t|
			wd = t.work_documents.first
			
			wd_tiers = Array.new
			wd_media = Array.new

			wd.document.tiers.each { |t| wd_tiers.push(t[:tier_id]) }
			wd.document.media_descriptors.each { |m| wd_media.push(m[:media_url]) }

			if (wd_tiers == self_tiers && wd_media == self_media)
					is_template = false
					self.template = t
					self.save
					break
			end
		end

		if (is_template)
			template = self.clone_for_template
			self.template = template
			self.save
		end
	end
end

app/controllers/work_documents_controller.rb
require 'elan_parser'
class WorkDocumentsController < ApplicationController
  before_filter :authenticate_user!

  def index
    @work_documents = WorkDocument.all

    respond_to do |format|
      format.html # index.html.erb
    end
  end

  # GET /work_documents/1/edit
  def edit
    @work_document = WorkDocument.find(params[:id])
    #@projects = Project.all
    #@selected_project = @work_document.project
  end

  # GET /work_documents/new
  def new
    @work_document = WorkDocument.new
    #@projects = Project.all

    respond_to do |format|
      format.html # new.html.erb
    end
  end

  # POST /work_documents
  def create

		@document = Document.new(:eaf => params[:work_document][:documents][:eaf])

		@work_document = WorkDocument.new(:document => @document, 
			:user_id => current_user.id)

    @document.create_annotation_document if @document.eaf?
		@document.save if @document.valid?

		@work_document.save

    respond_to do |format|
      if @work_document.valid?
        format.html { redirect_to @work_document, notice: 'Document was successfully created.' }
      else
        @document.destroy
        format.html { render action: "new" }
      end
    end
  end

  def show
    @work_document = WorkDocument.find(params[:id])
    #@projects = Project.all
    #@selected_project = @work_document.project

    respond_to do |format|
      format.html # show.html.erb
    end
  end

  # PUT /work_documents/1
  def update
    @work_document = WorkDocument.find(params[:id])
    #@projects = Project.all

    respond_to do |format|
      if @work_document.update_attributes(params[:work_document])
        format.html { redirect_to @work_document, notice: 'Work Document was successfully updated.' }
      else
        format.html { render action: "edit" }
      end
    end
  end

  # DELETE /work_documents/1
  def destroy
    @work_document = WorkDocument.find(params[:id])
    @work_document.destroy

    respond_to do |format|
      format.html { redirect_to work_documents_url }
    end
  end
end

app/views/work_documents/_form.html.erb
<%= form_for(@work_document) do |f| %>
  <% if @work_document.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@work_document.errors.count, "error") %> prohibited this work_document from being saved:</h2>

      <ul>
      <% @work_document.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :work_document_project %>
    <%= collection_select(:project, :project_id, @projects, :id, :project_name, 
      @selected_project.blank? ? {:prompt => "Please select"} : {:selected => @selected_project.id}) %>
  </div>
	<% if @selected_project.blank? or @work_document.errors.any? %>
		<%= f.fields_for :documents do |document_form| %>
			<div class="field">
				<% if !@work_document.document.nil? and @work_document.document.eaf? %>
					<p>Current Document: <%= File.basename(@work_document.document.eaf.to_s) %></p>
				<% end %>
				<%= document_form.file_field :eaf %>
				<%= document_form.hidden_field :eaf_cache %>
			</div>
		<% end %>
	<% end %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/work_documents/edit.html.erb
<h1>Editing document</h1>

<%= render 'form' %>

<%= link_to 'Show', :action => "show", :id => @work_document.id %> |
<%= link_to 'Back', work_documents_path %>

app/views/work_documents/index.html.erb
<h1>Listing Elan File</h1>

<table>
  <tr>
    <th>File Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @work_documents.each do |work_document| %>
  <tr>
    <td><%= File.basename(work_document.document.eaf.to_s) %></td>
    <td><%= link_to 'Download', download_document_path(work_document.document) %></td>
    <td><%= link_to 'Edit', edit_work_document_path(work_document) %></td>
    <td><%= link_to 'Destroy', work_document, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Document', new_work_document_path %>

app/views/work_documents/new.html.erb
<h1>New document</h1>

<%= render 'form' %>

<%= link_to 'Back', work_documents_path %>

app/views/work_documents/show.html.erb
<p>
  <b>File Name:</b>
  <%= File.basename(@work_document.document.eaf.to_s) %>
</p>

<% @work_document.media_assets.each do |matches| -%>
  <%= matches[0] %>
  <p>Assets that possibly match:</p>
  <ul>
    <% matches[1].each do |asset| %>
      <li>
        <%= link_to asset.file_name.path,  download_user_asset_path(asset.id) %>
      </li>
    <% end %>
  </ul>
<% end -%>

<div class="row">

<div class="span12">
<div id="viewer"></div>
</div>
</div>

<% if @work_document.ready? %>

  <script>
  $().conBrio( <%= @work_document.document.annotations.to_json.html_safe %>,
              <%= @work_document.document.tiers.to_json.html_safe %>)

  </script>

<% end %>